config/routes.rb
Rails.application.routes.draw do
  resources :sm_banks do
    member do
      get :resend_notification
    end
  end
  
  resources :sm_bank_accounts
  resources :sm_unapproved_records

  resources :sm_payments, only: [:index, :show] do
    collection do
      get :index
      get :index
    end
    
    member do
      get :steps
    end
  end
  
  get '/sm_banks/:id/audit_logs' => 'sm_banks#audit_logs'
  get '/sm_bank_accounts/:id/audit_logs' => 'sm_bank_accounts#audit_logs'
  get '/sm_banks/:id/approve' => "sm_banks#approve"
  get '/sm_bank_accounts/:id/approve' => 'sm_bank_accounts#approve'
  
  # operation_routes_for 'sm_payments'
end

app/models/sm_bank_account.rb
class SmBankAccount < ActiveRecord::Base
  include Approval
  include SmApproval
  
  belongs_to :created_user, :foreign_key =>'created_by', :class_name => 'User'
  belongs_to :updated_user, :foreign_key =>'updated_by', :class_name => 'User'

  belongs_to :sm_bank, :foreign_key => 'sm_code', :primary_key => 'code'

  validates_presence_of :sm_code, :customer_id, :account_no, :is_enabled

  validates :sm_code, format: {with: /\A[a-z|A-Z|0-9]+\z/, :message => 'Invalid format, expected format is : {[a-z|A-Z|0-9]}' }, length: { maximum: 20 }
  validates :customer_id, format: {with: /\A[0-9]+\z/, :message => 'Invalid format, expected format is : {[0-9]}'}, length: { minimum: 3, maximum: 15 }
  validates :account_no, format: {with: /\A[0-9]+\z/, :message => 'Invalid format, expected format is : {[0-9]}' }, length: { minimum: 1, maximum: 15 }

  validates :mmid, presence: true, format: {with: /\A[0-9]{7}+\z/, :message => 'Invalid format, expected format is : {[0-9]{7}}'}, length: { minimum: 7, maximum: 7 }, if: :is_mmid_and_mobile_no_mandatory?
  validates :mobile_no, presence: true, format: {with: /\A[0-9]{10}+\z/, :message => 'Invalid format, expected format is : {[0-9]{10}}'}, length: {maximum: 10, minimum: 10}, if: :is_mmid_and_mobile_no_mandatory?
  
  validates_uniqueness_of :sm_code, :scope => [:customer_id, :account_no, :approval_status]
  validates_uniqueness_of :account_no, :scope => [:approval_status]

  validate :validate_customer_id
  validate :validate_sm_code
  validate :is_mmid_and_mobile_no_mandatory?
  validate :validate_account, if: -> {"sm_bank.present? && sm_bank.imps_allowed=='Y'"}
  validate :validate_customer_with_fcr, if: -> {"sm_bank.present? && sm_bank.neft_allowed=='Y'"}

  def validate_customer_id
    sm_bank_accounts = SmBankAccount.where("customer_id = ?", customer_id)
    if !sm_bank_accounts.empty?
      matching_sm_bank_accounts = sm_bank_accounts.select{|sm_bank_account| sm_bank_account.sm_code == sm_code}
      errors.add(:customer_id, "already exists with different sub member bank") if matching_sm_bank_accounts.empty?
    end
  end

  def validate_sm_code
    errors.add(:sm_code, "is not present in bank") if self.sm_bank.nil?
  end

  def is_mmid_and_mobile_no_mandatory?
    (sm_bank.imps_allowed? ? true : false) if !sm_bank.nil?
  end
  
  def validate_customer_with_fcr
    fcr_customer = Fcr::Customer.find_by_cod_cust_id(self.customer_id)
    if fcr_customer.nil?
      errors.add(:customer_id, "no record found in FCR for #{self.customer_id}")
    else
      errors[:base] << "Required setup for NEFT transfer not found in FCR for #{self.customer_id}" unless fcr_customer.transfer_type_allowed?('NEFT')
    end
  end

  def validate_account
    fcr_customer = Fcr::Customer.find_by_cod_cust_id(self.customer_id)
    atom_customer_by_debit_acct = Atom::Customer.find_by_accountno(self.account_no)

    if fcr_customer.present? && atom_customer_by_debit_acct.present?
      errors.add(:account_no, "Required setup for IMPS transfer not found in ATOM for #{self.account_no}") unless atom_customer_by_debit_acct.imps_allowed?(fcr_customer.ref_phone_mobile)
    else
      errors.add(:customer_id, "no record found in FCR for #{self.customer_id}") if fcr_customer.nil?
      errors.add(:account_no, "no record found in ATOM for #{self.account_no}") if atom_customer_by_debit_acct.nil?
    end
  end
end

app/controllers/sm_bank_accounts_controller.rb
class SmBankAccountsController < ApplicationController
  authorize_resource
  before_action :authenticate_user!
  before_action :block_inactive_user!
  respond_to :json
  include ApplicationHelper
  include SmBankAccountsHelper
  
  def new
    @sm_bank_account = SmBankAccount.new
  end

  def create
    @sm_bank_account = SmBankAccount.new(params[:sm_bank_account])
    if !@sm_bank_account.valid?
      render "new"
    else
      @sm_bank_account.created_by = current_user.id
      @sm_bank_account.save!
      flash[:alert] = "Bank Account successfully #{@sm_bank_account.approved_id.nil? ? 'created' : 'updated'} and is pending for approval"
      redirect_to @sm_bank_account
    end
  end 

  def edit
    sm_bank_account = SmBankAccount.unscoped.find_by_id(params[:id])
    if sm_bank_account.approval_status == 'A' && sm_bank_account.unapproved_record.nil?
      params = (sm_bank_account.attributes).merge({:approved_id => sm_bank_account.id, :approved_version => sm_bank_account.lock_version})
      sm_bank_account = SmBankAccount.new(params)
    end
    @sm_bank_account = sm_bank_account
  end

  def update
    @sm_bank_account = SmBankAccount.unscoped.find_by_id(params[:id])
    @sm_bank_account.attributes = params[:sm_bank_account]
    if !@sm_bank_account.valid?
      render "edit"
    else
      @sm_bank_account.updated_by = current_user.id
      @sm_bank_account.save!
      flash[:alert] = 'Bank Account successfully modified and is pending for approval'
      redirect_to @sm_bank_account
    end
    rescue ActiveRecord::StaleObjectError
      @sm_bank_account.reload
      flash[:alert] = 'Someone edited the Bank Account the same time you did. Please re-apply your changes to the Bank Account'
      render "edit"
  end 

  def show
    @sm_bank_account = SmBankAccount.unscoped.find_by_id(params[:id])
  end

  def index
    if params[:advanced_search].present?
      sm_bank_accounts = find_sm_bank_accounts(params).order("id desc")
    else
      sm_bank_accounts = (params[:approval_status].present? and params[:approval_status] == 'U') ? SmBankAccount.unscoped.where("approval_status =?",'U').order("id desc") : SmBankAccount.order("id desc")
    end
    @sm_bank_accounts_count = sm_bank_accounts.count
    @sm_bank_accounts = sm_bank_accounts.paginate(:per_page => 10, :page => params[:page]) rescue []
  end

  def audit_logs
    @sm_bank_account = SmBankAccount.unscoped.find(params[:id]) rescue nil
    @audit = @sm_bank_account.audits[params[:version_id].to_i] rescue nil
  end
  
  def approve
    @sm_bank_account = SmBankAccount.unscoped.find(params[:id]) rescue nil
    SmBankAccount.transaction do
      approval = @sm_bank_account.approve
      if @sm_bank_account.save and approval.empty?
        flash[:alert] = "Bank Account record was approved successfully"
      else
        msg = approval.empty? ? @sm_bank_account.errors.full_messages : @sm_bank_account.errors.full_messages << approval
        flash[:alert] = msg
        raise ActiveRecord::Rollback
      end
    end
    redirect_to @sm_bank_account
  end

  private

  def sm_bank_account_params
    params.require(:sm_bank_account).permit(:sm_code, :customer_id, :account_no, :mmid, :mobile_no, 
                                            :created_by, :updated_by, :created_at, :updated_at, 
                                            :lock_version, :approval_status, :last_action, :approved_version, :approved_id,
                                            :is_enabled)
  end
end

app/helpers/sm_bank_accounts_helper.rb
module SmBankAccountsHelper
  def find_sm_bank_accounts(params)
    sm_bank_accounts = (params[:approval_status].present? and params[:approval_status] == 'U') ? SmBankAccount.unscoped : SmBankAccount
    sm_bank_accounts = sm_bank_accounts.where("sm_code IN (?)", params[:sm_code].split(",").collect(&:strip)) if params[:sm_code].present?
    sm_bank_accounts = sm_bank_accounts.where("is_enabled=?",params[:is_enabled]) if params[:is_enabled].present?
    sm_bank_accounts = sm_bank_accounts.where("customer_id IN (?)", params[:customer_id].split(",").collect(&:strip)) if params[:customer_id].present?
    sm_bank_accounts = sm_bank_accounts.where("account_no IN (?)", params[:account_no].downcase.split(",").collect(&:strip)) if params[:account_no].present?
    sm_bank_accounts
  end

  def sm_banks_for_select
    SmBank.all.collect { |m| [m.code, m.code] }
  end
end

app/views/sm_bank_accounts/_advanced_search.html.haml
= form_tag '', :method => 'get', :class => 'form-horizontal', :autocomplete=>"off" do
  .control-group
    = label_tag "Sub Member Code", "Sub Member Code", :class => 'control-label'
    = text_field_tag :sm_code, params[:sm_code]
  .control-group
    = label_tag "Enabled?", "Enabled?", :class => 'control-label'
    = select_tag :is_enabled, options_for_select([['Yes','Y'],['No','N']],params[:is_enabled]),:prompt => "ANY"
  .control-group
    = label_tag "Customer ID", "Customer ID", :class => 'control-label'
    = text_field_tag :customer_id, params[:customer_id]
  .control-group
    = label_tag "Account No", "Account No", :class => 'control-label'
    = text_field_tag :account_no, params[:account_no]
    = hidden_field_tag :approval_status, params[:approval_status]
  .form-actions
    = submit_tag "Search", :name => nil, :class => 'btn btn-primary', :id => "adv_search_button"
    = button_tag "Reset", :type => 'button', :value=>'Reset', :class => 'btn', :id => 'adv_search_reset_button'
  = hidden_field_tag :advanced_search, :true

:javascript
  var in_advanced_search = true;

app/views/sm_bank_accounts/_approve.html.haml
- can = can? :approve, @record
- approve_flag = @record.enable_approve_button?
%a.btn{"data-toggle" => "modal", :href => "#{!(can && approve_flag) ? '#' : '#myModalApprove'}", :role => "button", :class => "btn btn-primary #{(can && approve_flag) ? '' : 'disabled'}"} Approve
.modal.hide.fade{"id" => "myModalApprove", "aria-hidden" => "true", "aria-labelledby" => "  myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel  Approve
    #error_message{:style => 'color:red'}
  .modal-body
    = simple_form_for @record, :url => {:action => 'approve'}, :method => :get, :html=>{:id=>"transition"} do |ef|
      = ef.input :updated_by, :as => :hidden, :input_html => {:value => current_user.id}
      = submit_tag "Approve", :class=>"btn btn-primary transition_button", :id => "transition_button"
%p{:style => 'color:green;'}
  = created_or_edited_by(@record)
%br

app/views/sm_bank_accounts/_form.html.haml
= simple_form_for @sm_bank_account, :html => {:class=>'form-horizontal', :autocomplete=>"off", :id => "sm_bank_account_form"} do |f|
  .control-group
    = f.label ' '
    #msg-error
      = error_message_for(@sm_bank_account, :base, :prepend_text => "")
  .form-main{:style => "width: 100%;"}
    = f.hidden_field :lock_version
    = f.hidden_field :approved_id
    = f.hidden_field :approved_version
    .control-group
      = f.label :is_enabled, "Enabled?", :class => 'control-label'
      - if f.object.is_enabled.nil?
        = f.check_box :is_enabled, {:checked => "checked"},"Y","N"
      - else 
        = f.check_box :is_enabled, {},"Y","N"
      #msg-error
        = error_message_for(@sm_bank, :is_enabled, :prepend_text => "")
    - if f.object.sm_code.present?
      .control-group
        = f.label :sm_code, "*Sub Member Code", :class => 'control-label'
        = f.text_field :sm_code, readonly: true
        #msg-error
          = error_message_for(@sm_bank_account, :sm_code, :prepend_text => "")
    - else
      .control-group
        = f.label :sm_code, "*Sub Member Code", :class => 'control-label'
        = f.select(:sm_code, sm_banks_for_select, :prompt => 'Select')
        #msg-error
          = error_message_for(@sm_bank_account, :sm_code, :prepend_text => "")
    .control-group
      = f.label :customer_id, "*Customer ID", :class => 'control-label'
      = f.text_field :customer_id, :minlength => 3, :maxlength => 15, :required => true
      #msg-error
        = error_message_for(@sm_bank_account, :customer_id, :prepend_text => "")
    .control-group
      = f.label :account_no, "*Account No", :class => 'control-label'
      = f.text_field :account_no, :minlength => 1, :maxlength => 15, :required => true
      #msg-error
        = error_message_for(@sm_bank_account, :account_no, :prepend_text => "")
    .control-group
      = f.label :mmid, "MMID", :class => 'control-label'
      = f.text_field :mmid, :minlength => 7, :maxlength => 7
      #msg-error
        = error_message_for(@sm_bank_account, :mmid, :prepend_text => "")
    .control-group
      = f.label :mobile_no, "Mobile No", :class => 'control-label'
      = f.text_field :mobile_no, :minlength => 10, :maxlength => 10
      #msg-error
        = error_message_for(@sm_bank_account, :mobile_no, :prepend_text => "")
    
  .form-actions
    - (f.object.new_record? and f.object.sm_code.nil?) ? label_name = "Create" : label_name = "Update"
    = f.button "submit" ,:class=>"btn btn-primary", :id => 'submit_sm_bank_account', :value => label_name + ' Sub Member Bank Account'
    = link_to :Cancel,'/sm_bank_accounts', :name => 'cancel', :class=>"cancel btn"

app/views/sm_bank_accounts/audit_logs.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8;'}
    #form-details
      = form_for "audit_logs", :url => "", :method => :get do |f|
        %h3{:style => 'display:inline;'} 
          = "Values at version" 
          = select_tag :version_id, options_for_select(version_ids(@sm_bank_account),params[:version_id]), :prompt => 'Select'
          = submit_tag "Show", :name => nil, :class => "btn btn-primary"
      %br
      - unless @audit.nil?
        %table.table.no-border{:style=>"table-layout: fixed; width: 100%"}
          %tr
            %th Field
            %th Old Value
            %th New Value
          %tr
            %td.label 
              = "Change Done By"
            %td.value
              = " " 
            %td.value
              = @audit.user.username
          %tr
            %td.label 
              = "Action"
            %td.value
              = " " 
            %td.value
              = @audit.action
          - @audit.audited_changes.each do |change,value|
            %tr
              %td.label 
                = change
              %td.value
                = old_values(value)
              %td.value
                = new_values(value)

app/views/sm_bank_accounts/edit.html.haml
%h1 Editing Sub Member Bank Account

= render 'form'

app/views/sm_bank_accounts/index.html.haml
%br
= link_to 'New Sub Member Bank Account', new_sm_bank_account_path
%br
%br
%h1 Listing Sub Member Bank Accounts
%h2.collapsible
  Advanced Search
  %span.caret
.collapsible-content
  = render :partial => 'advanced_search'
%br
= "Total Count: #{@sm_bank_accounts_count}"
%br
= will_paginate @sm_bank_accounts
%br

%table.table.table-bordered.table-striped.table-hover
  .thead
    %th{:style=>'text-align:left; background-color: lightblue;'}
    %th{:style=>'text-align:left; background-color: lightblue;'}
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Enabled?
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Sub Member Code
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Customer ID
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Account No
    %th{:style=>'text-align:left; background-color: lightblue;'}
      MMID
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Mobile No

  .tbody
    - @sm_bank_accounts.each do |sm_bank_account|
      %tr
        %td{:style=>'text-align:left;'}
          = link_to 'Show', sm_bank_account
        %td{:style=>'text-align:left;'}
          = link_to 'Edit', edit_sm_bank_account_path(sm_bank_account)
        %td{:style=>'text-align:left;'}
          = sm_bank_account.is_enabled
        %td{:style=>'text-align:left;'}
          = sm_bank_account.sm_code
        %td{:style=>'text-align:left;'}
          = sm_bank_account.customer_id
        %td{:style=>'text-align:left;'}
          = sm_bank_account.account_no
        %td{:style=>'text-align:left;'}
          = sm_bank_account.mmid
        %td{:style=>'text-align:left;'}
          = sm_bank_account.mobile_no

:javascript
  $(document).ready(function(){
    $('input[type="text"]'). attr("placeholder", "Multisearch Search Enabled");
  });

app/views/sm_bank_accounts/new.html.haml
%h1 New Sub Member Bank Account

= render 'form'

app/views/sm_bank_accounts/show.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8; height: 900px;'}
    #form-details
      %h3 Sub Member Bank Account Details 
      %br
      %p{:style => 'text-align:left; padding-left:6px; padding-bottom:17px'}
        - can = can? :edit, @sm_bank_account
        %a.btn{:href => "#{!(can) ? '#' : '/sm_bank_accounts/' + @sm_bank_account.id.to_s + '/edit'}", :role => "button", :class => "btn btn-primary #{(can) ? '' : 'disabled'}"} Edit
        = render 'approve', :@record => @sm_bank_account
      %table.table.no-border{:style=>"table-layout: fixed; width: 100%;"}
        - if !@sm_bank_account.nil?
          %tr
            %td.label Version
            %td.value
              = link_to "#{audit_count(@sm_bank_account)}", :controller => :sm_bank_accounts, :action => :audit_logs, :version_id => audit_count(@sm_bank_account), :id => @sm_bank_account.id
          %tr
            %td.label Form Errors
            %td.value
              = ' '
            %td#msg-error
              = error_message_for(@sm_bank_account, :base, :prepend_text => "")
          %tr
            %td.label Enabled?
            %td.value
              = @sm_bank_account.is_enabled
            %td#msg-error
              = error_message_for(@sm_bank_account, :is_enabled, :prepend_text => "")
          %tr
            %td.label Sub Member Code
            %td.value
              = @sm_bank_account.sm_code
            %td#msg-error
              = error_message_for(@sm_bank_account, :sm_code, :prepend_text => "")
          %tr
            %td.label Customer ID
            %td.value
              = @sm_bank_account.customer_id
            %td#msg-error
              = error_message_for(@sm_bank_account, :customer_id, :prepend_text => "")
          %tr
            %td.label Account No
            %td.value
              = @sm_bank_account.account_no
            %td#msg-error
              = error_message_for(@sm_bank_account, :account_no, :prepend_text => "")
          %tr
            %td.label MMID
            %td.value
              = @sm_bank_account.mmid
            %td#msg-error
              = error_message_for(@sm_bank_account, :mmid, :prepend_text => "")
          %tr
            %td.label Mobile No
            %td.value
              = @sm_bank_account.mobile_no
            %td#msg-error
              = error_message_for(@sm_bank_account, :mobile_no, :prepend_text => "")
          %tr
            %td.label Created By
            %td.value
              = @sm_bank_account.created_user.try(:username)
            %td#msg-error
              = error_message_for(@sm_bank_account, :created_by, :prepend_text => "")
          %tr
            %td.label Updated By
            %td.value
              = @sm_bank_account.updated_user.try(:username)
            %td#msg-error
              = error_message_for(@sm_bank_account, :updated_by, :prepend_text => "")
          %tr
            %td.label Created At
            %td.value
              = @sm_bank_account.created_at.try(:strftime, "%d/%m/%Y %I:%M%p")
            %td#msg-error
              = error_message_for(@sm_bank_account, :created_at, :prepend_text => "")
          %tr
            %td.label Updated At
            %td.value
              = @sm_bank_account.updated_at.try(:strftime, "%d/%m/%Y %I:%M%p")
            %td#msg-error
              = error_message_for(@sm_bank_account, :updated_at, :prepend_text => "")