config/routes.rb
Rails.application.routes.draw do
  resources :sm_banks do
    member do
      get :resend_notification
    end
  end
  
  resources :sm_bank_accounts
  resources :sm_unapproved_records

  resources :sm_payments, only: [:index, :show] do
    collection do
      get :index
      get :index
    end
    
    member do
      get :steps
    end
  end
  
  get '/sm_banks/:id/audit_logs' => 'sm_banks#audit_logs'
  get '/sm_bank_accounts/:id/audit_logs' => 'sm_bank_accounts#audit_logs'
  get '/sm_banks/:id/approve' => "sm_banks#approve"
  get '/sm_bank_accounts/:id/approve' => 'sm_bank_accounts#approve'
  
  # operation_routes_for 'sm_payments'
end

app/models/sm_payment.rb
class SmPayment < ActiveRecord::Base
  include SearchAbility
  
  attr_searchable :req_no, :customer_id, :status_code, :attempt_no, :transfer_type, :partner_code, :debit_account_no, :rmtr_account_no, :rmtr_account_ifsc, :bene_account_no, :bank_ref_no, {req_timestamp: :range}, {rep_timestamp: :range} 

  has_many :audit_steps, :class_name => 'SmAuditStep', :as => :sm_auditable
  has_one :audit_log, class_name: 'SmAuditLog', :as => :sm_auditable
  
  as_enum :status_code, [:'FAILED', :'COMPLETED', :'IN_PROCESS', :'SENT_TO_BENEFICIARY', :'RETURNED_FROM_BENEFICIARY', :'SCHEDULED_FOR_NEXT_WORKDAY'], map: :string, source: :status_code
  as_enum :transfer_type, [:NEFT, :IMPS, :RTGS, :FT], map: :string, source: :transfer_type
end

app/controllers/sm_payments_controller.rb
class SmPaymentsController < ApplicationController
  authorize_resource
  before_action :authenticate_user!
  before_action :block_inactive_user!
  include SmPaymentHelper

  def index
    authorize SmPayment
    if params[:advanced_search].present?
      sm_payments = find_sm_payments(params).order("id DESC")
    else
      sm_payments = SmPayment.order("id desc")
    end
    @sm_payments = sm_payments.paginate(:per_page => 10, :page => params[:page]) rescue []
  end
  
  def show
    authorize @sm_payment = SmPayment.find(params[:id]).decorate
  end

  def steps
    authorize r = SmPayment.find(params[:id])
    @steps = SmPaymentDecorator.decorate_collection(r.audit_steps)
    render '/audit_steps/index'
  end
  
end

app/helpers/sm_payment_helper.rb
module SmPaymentHelper
  def find_sm_payments(params)
    sm_payments = SmPayment
    sm_payments = sm_payments.where("req_no IN (?)", params[:req_no].split(",").collect(&:strip)) if params[:req_no].present?
    sm_payments = sm_payments.where("customer_id IN (?)", params[:customer_id].split(",").collect(&:strip)) if params[:customer_id].present?
    sm_payments = sm_payments.where("status_code = ?", params[:status_code]) if params[:status_code].present?
    sm_payments = sm_payments.where("transfer_type = ?", params[:transfer_type]) if params[:transfer_type].present?
    sm_payments = sm_payments.where("partner_code IN (?)", params[:partner_code].split(",").collect(&:strip)) if params[:partner_code].present?
    sm_payments = sm_payments.where("debit_account_no IN (?)", params[:debit_account_no].split(",").collect(&:strip)) if params[:debit_account_no].present?
    sm_payments = sm_payments.where("rmtr_account_no IN (?)", params[:rmtr_account_no].split(",").collect(&:strip)) if params[:rmtr_account_no].present?
    sm_payments = sm_payments.where("rmtr_account_ifsc IN (?)", params[:rmtr_account_ifsc].split(",").collect(&:strip)) if params[:rmtr_account_ifsc].present?
    sm_payments = sm_payments.where("bene_account_no IN (?)", params[:bene_account_no].split(",").collect(&:strip)) if params[:bene_account_no].present?
    sm_payments = sm_payments.where("bank_ref_no IN (?)", params[:bank_ref_no].split(",").collect(&:strip)) if params[:bank_ref_no].present?
    sm_payments = sm_payments.where("req_timestamp>=? and req_timestamp<=?",Time.zone.parse(params[:from_req_timestamp]).beginning_of_day,Time.zone.parse(params[:to_req_timestamp]).end_of_day) if params[:from_req_timestamp].present? and params[:to_req_timestamp].present?
    sm_payments = sm_payments.where("rep_timestamp>=? and rep_timestamp<=?",Time.zone.parse(params[:from_rep_timestamp]).beginning_of_day,Time.zone.parse(params[:to_rep_timestamp]).end_of_day) if params[:from_rep_timestamp].present? and params[:to_rep_timestamp].present?
    sm_payments
  end
end

app/views/sm_payments/_advanced_search.html.haml
= form_tag '', :method => 'get', :class => 'form-horizontal', :autocomplete=>"off" do
  .control-group
    = label_tag "Request No", "Request No", :class => 'control-label'
    = text_field_tag :req_no, params[:req_no],placeholder: 'Multisearch Search Enabled'
  - if current_user.present? && current_user.try(:accessible_customers).try(:count) != 1
    .control-group
      = label_tag "Customer ID", "Customer ID", :class => 'control-label'
      = text_field_tag :customer_id, params[:customer_id],placeholder: 'Multisearch Search Enabled'
  .control-group
    = label_tag "Status Code", "Status Code", :class => 'control-label'
    = select_tag :status_code, options_for_select([['FAILED','FAILED'],['COMPLETED','COMPLETED'],['IN_PROCESS','IN_PROCESS'],['SENT_TO_BENEFICIARY','SENT_TO_BENEFICIARY'],['RETURNED_FROM_BENEFICIARY','RETURNED_FROM_BENEFICIARY'],['SCHEDULED_FOR_NEXT_WORKDAY','SCHEDULED_FOR_NEXT_WORKDAY']],params[:status_code]),:prompt => 'ANY'
  .control-group
    = label_tag "Attempt No", "Attempt No", :class => 'control-label'
    = number_field_tag :attempt_no, params[:attempt_no],placeholder: 'Multisearch Search Enabled'
  .control-group
    = label_tag "Transfer Type", "Transfer Type", :class => 'control-label'
    = select_tag :transfer_type, options_for_select([['NEFT','NEFT'],['IMPS','IMPS'],['RTGS','RTGS'],['FT','FT']],params[:transfer_type]),:prompt => 'ANY'
  .control-group
    = label_tag "Partner Code", "Partner Code", :class => 'control-label'
    = number_field_tag :partner_code, params[:partner_code],placeholder: 'Multisearch Search Enabled'
  .control-group
    = label_tag "Debit Account No", "Debit Account No", :class => 'control-label'
    = number_field_tag :debit_account_no, params[:debit_account_no],placeholder: 'Multisearch Search Enabled'
  .control-group
    = label_tag "Remitter Account No", "Remitter Account No", :class => 'control-label'
    = number_field_tag :rmtr_account_no, params[:rmtr_account_no],placeholder: 'Multisearch Search Enabled'
  .control-group
    = label_tag "Remitter Account IFSC", "Remitter Account IFSC", :class => 'control-label'
    = number_field_tag :rmtr_account_ifsc, params[:rmtr_account_ifsc],placeholder: 'Multisearch Search Enabled'
  .control-group
    = label_tag "Beneficiary Account Number", "Beneficiary Account Number", :class => 'control-label'
    = number_field_tag :bene_account_no, params[:bene_account_no],placeholder: 'Multisearch Search Enabled'
  .control-group
    = label_tag "Bank Reference No", "Bank Reference No", :class => 'control-label'
    = number_field_tag :bank_ref_no, params[:bank_ref_no],placeholder: 'Multisearch Search Enabled'
  .control-group
    = label_tag "Request Timestamp", "Request Timestamp", :class => 'control-label'
    = date_field_tag(:from_req_timestamp, params[:from_req_timestamp])
    To
    = date_field_tag(:to_req_timestamp, params[:to_req_timestamp])
  .control-group
    = label_tag "Reply Timestamp", "Reply Timestamp", :class => 'control-label'
    = date_field_tag(:from_rep_timestamp, params[:from_rep_timestamp])
    To
    = date_field_tag(:to_rep_timestamp, params[:to_rep_timestamp])
  .form-actions
    = button_tag "Search", :class => 'btn btn-primary'
    = button_tag "Reset", :type => 'button', :value=>'Reset', :class => 'btn', :id => 'sm_paymment_reset'
  = hidden_field_tag :advanced_search, :true


:javascript
  $("#sm_paymment_reset").click(function() {
    $(this).closest('form').find("input,select").val("");
  });

app/views/sm_payments/index.html.haml
/ - index_model = SmPayment
/ - index_columns = [:req_no, :status_code, :customer_id, :partner_code, :debit_account_no, :rmtr_account_no, :rmtr_account_ifsc, :transfer_type, :req_timestamp, :rep_timestamp, :attempt_no,  :user_action]

/ = render partial: 'shared/index', locals: {index_model: index_model, index_columns: index_columns, records: @records


%h1 Listing Sm payments
%h2.collapsible
  Advanced Search
  %span.caret
.collapsible-content
  = render :partial => 'advanced_search'
%br
= "Total Count: #{@sm_payments.count}"
= will_paginate @sm_payments, :page_links => true
%br
%table.table.table-bordered.table-striped.table-hover
  .thead
    %th{:style=>'text-align:left; background-color: lightblue;'}
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Request No  
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Status Code
    - if current_user.present? && current_user.try(:accessible_customers).try(:count) != 1
      %th{:style=>'text-align:left; background-color: lightblue;'}
        Customer ID 
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Partner Code
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Debit Account No
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Remitter Account No
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Remitter Account IFSC
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Request Timestamp
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Reply Timestamp
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Attempt No

  .tbody
    - @sm_payments.each do |sm_payment|
      %tr
        %td{:style=>'text-align:left;'}
          = link_to 'Show', sm_payment
        %td{:style=>'text-align:left;'}
          = sm_payment.req_no
        %td{:style=>'text-align:left;'}
          = render partial: 'shared/status', locals: {id: "#{sm_payment.class.name.demodulize}_status_code_#{sm_payment.id}", object: sm_payment}
        - if current_user.present? && current_user.try(:accessible_customers).try(:count) != 1
          %td{:style=>'text-align:left;'}
            = sm_payment.customer_id
        %td{:style=>'text-align:left;'}
          = sm_payment.partner_code
        %td{:style=>'text-align:left;'}
          = sm_payment.debit_account_no
        %td{:style=>'text-align:left;'}
          = sm_payment.rmtr_account_no
        %td{:style=>'text-align:left;'}
          = sm_payment.rmtr_account_ifsc
        %td{:style=>'text-align:left;'}
          = sm_payment.req_timestamp.try(:strftime, "%d/%m/%Y %I:%M%p")
        %td{:style=>'text-align:left;'}
          = sm_payment.rep_timestamp.try(:strftime, "%d/%m/%Y %I:%M%p")
        %td{:style=>'text-align:left;'}
          = sm_payment.attempt_no

app/views/sm_payments/show.html.haml
/ - panel = [[],[],[]]
/ - panel[0] << {title: 'Request', height: '170px', fields: [:request, :partner_code, :req_timestamp]}
/ - panel[0] << {title: 'Request', height: '170px', fields: [:reply, :status_code, :bank_ref_no, :rep_timestamp, :reconciled_at, :steps]}
/ - panel[1] << {title: 'Request Details', height: '300px', fields: [:req_version, :customer_id, :debit_account_no, :rmtr_account_no, :rmtr_account_ifsc, :transfer_type, :req_transfer_type]}
/ - panel[1] << {title: '', height: '300px', fields: [:transfer_ccy, :transfer_amount, :bene_account_no, :bene_account_ifsc, :cbs_req_ref_no, :rmtr_to_bene_note]}
/ - panel[2] << {title: 'Remitter Details', height: '400px', fields: [:rmtr_full_name, :rmtr_address1, :rmtr_address2, :rmtr_address3, :rmtr_postal_code, :rmtr_city, :rmtr_state, :rmtr_country, :rmtr_email_id, :rmtr_mobile_no]}
/ - panel[2] << {title: 'Beneficiary Details', height: '400px', fields: [:bene_full_name, :bene_address1, :bene_address2, :bene_address3, :bene_postal_code, :bene_city, :bene_state, :bene_country, :bene_email_id, :bene_mobile_no]}

/ = render partial: 'shared/show', locals: {record: @record, toolbar: nil, panel: panel}


- unless @sm_payment.nil?
  .show_ticket      
    .header-form-main{:style=>'background-color: #F1F2F8; width: 50%; height: 158px; display: inline-block;'}
      %h3
        Request:
        = @sm_payment.request
      %h3
        Partner Code:
        = @sm_payment.partner_code
      %h3
        Request Timestamp:
        = @sm_payment.req_timestamp
    .header-form-main{:style=>'background-color: #F1F2F8; width: 50%; height: 158px; display: inline-block;'}
      %h3 
        Reply:
        = @sm_payment.reply
      %h3 
        Status Code:
        = @sm_payment.status_code
      %h3
        Bank Reference No:
        = @sm_payment.bank_ref_no
      %h3
        Reply Timestamp:
        = @sm_payment.rep_timestamp
      %h3
        Reconciled At:
        = @sm_payment.reconciled_at
      %h3
        Steps:
        = link_to 'Show',steps_sm_payment_path(id: @sm_payment.id)
    .header-form-main{:style=>'background-color: #ecf5fa; width: 50%; height: 300px; display: inline-block;'}
      #ticket-details
        %h3
          Request Details
        %table.table.no-border{:style=>"table-layout: fixed; width: 100%"}
          %tr
            %td.label Request Version
            %td.value
              = @sm_payment.req_version
          %tr
            %td.label Customer ID
            %td.value
              = @sm_payment.customer_id
          %tr
            %td.label Debit Account No
            %td.value
              = @sm_payment.debit_account_no
          %tr
            %td.label Remitter Account No
            %td.value
              = @sm_payment.rmtr_account_no
          %tr
            %td.label Remitter Account IFSC
            %td.value
              = @sm_payment.rmtr_account_ifsc
          %tr
            %td.label Transfer Type
            %td.value
              = @sm_payment.transfer_type
          %tr
            %td.label Request Transfer Type
            %td.value
              = @sm_payment.req_transfer_type
    .header-form-main{:style=>'background-color: #ecf5fa; width: 50%; height: 300px; display: inline-block;'}
      #ticket-details
        %table.table.no-border{:style=>"table-layout: fixed; width: 100%"}
          %tr
            %td.label Transfer Currency
            %td.value
              = @sm_payment.transfer_ccy
          %tr
            %td.label Transfer Amount
            %td.value
              = @sm_payment.transfer_amount
          %tr
            %td.label Beneficiary Account Number
            %td.value
              = @sm_payment.bene_account_no
          %tr
            %td.label Beneficiary Account IFSC
            %td.value
              = @sm_payment.bene_account_ifsc
          %tr
            %td.label CBS Request Reference No
            %td.value
              = @sm_payment.cbs_req_ref_no
          %tr
            %td.label Remitter To Bene Note
            %td.value
              = @sm_payment.rmtr_to_bene_note
    .header-form-main{:style=>'background-color: #F1F2F8; width: 50%; height: 400px; display: inline-block;'}
      #ticket-details
        %h3
          Remitter Details
        %table.table.no-border{:style=>"table-layout: fixed; width: 100%"}
          %tr
            %td.label Name
            %td.value
              = @sm_payment.rmtr_full_name
          %tr
            %td.label Address
            %td.value
              = "#{@sm_payment.rmtr_address1}"
              %br
              = "#{@sm_payment.rmtr_address2}"
              %br
              = "#{@sm_payment.rmtr_address3}"
          %tr
            %td.label Postal Code
            %td.value
              = @sm_payment.rmtr_postal_code
          %tr
            %td.label City
            %td.value
              = @sm_payment.rmtr_city
          %tr
            %td.label State
            %td.value
              = @sm_payment.rmtr_state
          %tr
            %td.label Country
            %td.value
              = @sm_payment.rmtr_country
          %tr
            %td.label Email
            %td.value
              = @sm_payment.rmtr_email_id
          %tr
            %td.label Mobile No
            %td.value
              = @sm_payment.rmtr_mobile_no
    .header-form-main{:style=>'background-color: #F1F2F8; width: 50%; height: 400px; display: inline-block;'}
      #ticket-details
        %h3
          Beneficiary Details
        %table.table.no-border{:style=>"table-layout: fixed; width: 100%"}
          %tr
            %td.label Name
            %td.value
              = @sm_payment.bene_full_name
          %tr
            %td.label Address
            %td.value
              = "#{@sm_payment.bene_address1}"
              %br
              = "#{@sm_payment.bene_address2}"
              %br
              = "#{@sm_payment.bene_address3}"
          %tr
            %td.label Postal Code
            %td.value
              = @sm_payment.bene_postal_code
          %tr
            %td.label City
            %td.value
              = @sm_payment.bene_city
          %tr
            %td.label State
            %td.value
              = @sm_payment.bene_state
          %tr
            %td.label Country
            %td.value
              = @sm_payment.bene_country
          %tr
            %td.label Email
            %td.value
              = @sm_payment.bene_email_id
          %tr
            %td.label Beneficiary Mobile No
            %td.value
              = @sm_payment.bene_mobile_no