config/routes.rb
Rails.application.routes.draw do
  resources :sm_banks do
    member do
      get :resend_notification
    end
  end
  
  resources :sm_bank_accounts
  resources :sm_unapproved_records

  resources :sm_payments, only: [:index, :show] do
    collection do
      get :index
      get :index
    end
    
    member do
      get :steps
    end
  end
  
  get '/sm_banks/:id/audit_logs' => 'sm_banks#audit_logs'
  get '/sm_bank_accounts/:id/audit_logs' => 'sm_bank_accounts#audit_logs'
  get '/sm_banks/:id/approve' => "sm_banks#approve"
  get '/sm_bank_accounts/:id/approve' => 'sm_bank_accounts#approve'
  
  # operation_routes_for 'sm_payments'
end

app/models/sm_bank.rb
class SmBank < ActiveRecord::Base
  include Approval
  include SmApproval
  include ServiceNotification
  
  belongs_to :created_user, :foreign_key =>'created_by', :class_name => 'User'
  belongs_to :updated_user, :foreign_key =>'updated_by', :class_name => 'User'

  has_many :sm_bank_accounts, :primary_key => 'code', :foreign_key => 'sm_code', :class_name => 'SmBankAccount'

  validates_presence_of :code, :name, :bank_code, :identity_user_id, :neft_allowed, :imps_allowed, :is_enabled

  validates :code, format: {with: /\A[a-z|A-Z|0-9]+\z/, :message => 'Invalid format, expected format is : {[a-z|A-Z|0-9]}' }, length: {maximum: 20}
  validates :name, format: {with: /\A[a-z|A-Z|0-9|\s|\.|\-]+\z/, :message => 'Invalid format, expected format is : {[a-z|A-Z|0-9|\s|\.|\-]}' }, length: {maximum: 100}
  # validates :bank_code, format: {with: /\A[A-Z]{4}[0][A-Z]{3}[A-Z|0-9]{3}+\z/, message: "invalid format - expected format is : {[A-Z]{4}[0][A-Z]{3}[A-Z|0-9]{3}}" }
  validates :low_balance_alert_at, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => '9e20'.to_f }
  validates :identity_user_id, format: {with: /\A[a-z|A-Z|0-9]+\z/, :message => 'Invalid format, expected format is : {[a-z|A-Z|0-9]}'}, length: {maximum: 20}

  validate :presence_of_iam_cust_user

  validates_uniqueness_of :code, :scope => :approval_status

  def imps_allowed?
    imps_allowed == "Y" ? true : false
  end

  def presence_of_iam_cust_user
    errors.add(:identity_user_id, 'IAM Customer User does not exist for this username') unless IamCustUser.iam_cust_user_exists?
  end

  def template_variables
    user = IamCustUser.find_by(username: identity_user_id)
    { username: user.try(:username), first_name: user.try(:first_name), last_name: user.try(:last_name), mobile_no: user.try(:mobile_no),
      email: user.try(:email), service_name: 'DomesticRemittance', partner_code: code, customer_id: sm_bank_accounts.first.try(:customer_id),
      account_no: sm_bank_accounts.first.try(:account_no) }
  end
end

app/controllers/sm_banks_controller.rb
class SmBanksController < ApplicationController
  authorize_resource
  before_action :authenticate_user!
  before_action :block_inactive_user!
  respond_to :json
  include ApplicationHelper
  include SmBanksHelper
  
  def new
    @sm_bank = SmBank.new
  end

  def create
    @sm_bank = SmBank.new(params[:sm_bank])
    if !@sm_bank.valid?
      render "new"
    else
      @sm_bank.created_by = current_user.id
      @sm_bank.save!
      flash[:alert] = "Bank successfully #{@sm_bank.approved_id.nil? ? 'created' : 'updated'} and is pending for approval"
      redirect_to @sm_bank
    end
  end 

  def edit
    sm_bank = SmBank.unscoped.find_by_id(params[:id])
    if sm_bank.approval_status == 'A' && sm_bank.unapproved_record.nil?
      params = (sm_bank.attributes).merge({:approved_id => sm_bank.id, :approved_version => sm_bank.lock_version})
      sm_bank = SmBank.new(params)
    end
    @sm_bank = sm_bank
  end

  def update
    @sm_bank = SmBank.unscoped.find_by_id(params[:id])
    @sm_bank.attributes = params[:sm_bank]
    if !@sm_bank.valid?
      render "edit"
    else
      @sm_bank.updated_by = current_user.id
      @sm_bank.save!
      flash[:alert] = 'Bank successfully modified and is pending for approval'
      redirect_to @sm_bank
    end
    rescue ActiveRecord::StaleObjectError
      @sm_bank.reload
      flash[:alert] = 'Someone edited the Bank the same time you did. Please re-apply your changes to the Bank'
      render "edit"
  end 

  def show
    @sm_bank = SmBank.unscoped.find_by_id(params[:id])
  end

  def index
    if params[:advanced_search].present?
      sm_banks = find_sm_banks(params).order("id desc")
    else
      sm_banks = (params[:approval_status].present? and params[:approval_status] == 'U') ? SmBank.unscoped.where("approval_status =?",'U').order("id desc") : SmBank.order("id desc")
    end
    @sm_banks_count = sm_banks.count
    @sm_banks = sm_banks.paginate(:per_page => 10, :page => params[:page]) rescue []
  end

  def audit_logs
    @sm_bank = SmBank.unscoped.find(params[:id]) rescue nil
    @audit = @sm_bank.audits[params[:version_id].to_i] rescue nil
  end
  
  def approve
    @sm_bank = SmBank.unscoped.find(params[:id]) rescue nil
    SmBank.transaction do
      approval = @sm_bank.approve
      if @sm_bank.save and approval.empty?
        flash[:alert] = "Bank record was approved successfully"
      else
        msg = approval.empty? ? @sm_bank.errors.full_messages : @sm_bank.errors.full_messages << approval
        flash[:alert] = msg
        raise ActiveRecord::Rollback
      end
    end
    redirect_to @sm_bank
  end

  def resend_notification
    @sm_bank = SmBank.find(params[:id]) rescue nil
    flash[:alert] = @sm_bank.resend_setup
    redirect_to @sm_bank
  end

  private

  def sm_bank_params
    params.require(:sm_bank).permit(:code, :name, :bank_code, :low_balance_alert_at, :identity_user_id, :neft_allowed, :imps_allowed, :rtgs_allowed, :is_enabled,  
                                    :created_by, :updated_by, :created_at, :updated_at, 
                                    :lock_version, :approval_status, :last_action, :approved_version, :approved_id, :notification_sent_at)
  end
end

app/helpers/sm_banks_helper.rb
module SmBanksHelper
  def find_sm_banks(params)
    sm_banks = (params[:approval_status].present? and params[:approval_status] == 'U') ? SmBank.unscoped : SmBank
    sm_banks = sm_banks.where("code IN (?)", params[:code].split(",").collect(&:strip)) if params[:code].present?
    sm_banks = sm_banks.where("is_enabled=?",params[:is_enabled]) if params[:is_enabled].present?
    sm_banks = sm_banks.where("name IN (?)", params[:name].split(",").collect(&:strip)) if params[:name].present?
    sm_banks = sm_banks.where("bank_code IN (?)", params[:bank_code].split(",").collect(&:strip)) if params[:bank_code].present?
    sm_banks
  end
end

app/views/sm_banks/_advanced_search.html.haml
= form_tag '', :method => 'get', :class => 'form-horizontal', :autocomplete=>"off" do
  .control-group
    = label_tag "SMB Code", "SMB Code", :class => 'control-label'
    = text_field_tag :code, params[:code]
  .control-group
    = label_tag "Enabled?", "Enabled?", :class => 'control-label'
    = select_tag :is_enabled, options_for_select([['Yes','Y'],['No','N']],params[:is_enabled]),:prompt => "ANY"
  .control-group
    = label_tag "Name", "Name", :class => 'control-label'
    = text_field_tag :name, params[:name]
  .control-group
    = label_tag "SMB IFSC Code", "SMB IFSC Code", :class => 'control-label'
    = text_field_tag :bank_code, params[:bank_code]
    = hidden_field_tag :approval_status, params[:approval_status]
  .form-actions
    = submit_tag "Search", :name => nil, :class => 'btn btn-primary', :id => "adv_search_button"
    = button_tag "Reset", :type => 'button', :value=>'Reset', :class => 'btn', :id => 'adv_search_reset_button'
  = hidden_field_tag :advanced_search, :true

:javascript
  var in_advanced_search = true;

app/views/sm_banks/_form.html.haml
= simple_form_for @sm_bank, :html => {:class=>'form-horizontal', :autocomplete=>"off", :id => "sm_bank_form"} do |f|
  .control-group
    = f.label ' '
    #msg-error
      = error_message_for(@sm_bank, :base, :prepend_text => "")
  .form-main{:style => "width: 100%;"}
    = f.hidden_field :lock_version
    = f.hidden_field :approved_id
    = f.hidden_field :approved_version
    .control-group
      = f.label :is_enabled, "Enabled?", :class => 'control-label'
      - if f.object.is_enabled.nil?
        = f.check_box :is_enabled, {:checked => "checked"},"Y","N"
      - else 
        = f.check_box :is_enabled, {},"Y","N"
      #msg-error
        = error_message_for(@sm_bank, :is_enabled, :prepend_text => "")
    .control-group
      = f.label :code, "*SMB Code", :class => 'control-label'
      = f.text_field :code, :maxlength => 20, :required => true
      #msg-error
        = error_message_for(@sm_bank, :code, :prepend_text => "")
    .control-group
      = f.label :name, "*Name", :class => 'control-label'
      = f.text_field :name, :maxlength => 100, :required => true
      #msg-error
        = error_message_for(@sm_bank, :name, :prepend_text => "")
    .control-group
      = f.label :bank_code, "*SMB IFSC Code", :class => 'control-label'
      = f.text_field :bank_code, :maxlength => 11, :required => true
      #msg-error
        = error_message_for(@sm_bank, :bank_code, :prepend_text => "")
    .control-group
      = f.label :low_balance_alert_at, "Low Balance Alert At", :class => 'control-label'
      = f.text_field :low_balance_alert_at
      #msg-error
        = error_message_for(@sm_bank, :low_balance_alert_at, :prepend_text => "")
    .control-group
      = f.label :identity_user_id, "*Identity User ID", :class => 'control-label'
      = f.text_field :identity_user_id, :maxlength => 20
      #msg-error
        = error_message_for(@sm_bank, :identity_user_id, :prepend_text => "")
    .control-group
      = f.label :neft_allowed, "NEFT Allowed?", :class => 'control-label'
      - if f.object.neft_allowed.nil?
        = f.check_box :neft_allowed, {:checked => "checked"},"Y","N"
      - else 
        = f.check_box :neft_allowed, {},"Y","N"
      #msg-error
        = error_message_for(@sm_bank, :neft_allowed, :prepend_text => "")
    .control-group
      = f.label :imps_allowed, "IMPS Allowed?", :class => 'control-label'
      = f.check_box :imps_allowed, {},"Y","N"
    .control-group
      = f.label :rtgs_allowed, "RTGS Allowed?", :class => 'control-label'
      = f.check_box :rtgs_allowed, {},"Y","N"
      #msg-error
        = error_message_for(@sm_bank, :imps_allowed, :prepend_text => "")
  .form-actions
    - (f.object.new_record? and f.object.code.nil?) ? label_name = "Create" : label_name = "Update"
    = f.button "submit" ,:class=>"btn btn-primary", :id => 'submit_sm_bank', :value => label_name + ' Sub Member Bank'
    = link_to :Cancel,'/sm_banks', :name => 'cancel', :class=>"cancel btn"

app/views/sm_banks/audit_logs.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8;'}
    #form-details
      = form_for "audit_logs", :url => "", :method => :get do |f|
        %h3{:style => 'display:inline;'} 
          = "Values at version" 
          = select_tag :version_id, options_for_select(version_ids(@sm_bank),params[:version_id]), :prompt => 'Select'
          = submit_tag "Show", :name => nil, :class => "btn btn-primary"
      %br
      - unless @audit.nil?
        %table.table.no-border{:style=>"table-layout: fixed; width: 100%"}
          %tr
            %th Field
            %th Old Value
            %th New Value
          %tr
            %td.label 
              = "Change Done By"
            %td.value
              = " " 
            %td.value
              = @audit.user.username
          %tr
            %td.label 
              = "Action"
            %td.value
              = " " 
            %td.value
              = @audit.action
          - @audit.audited_changes.each do |change,value|
            %tr
              %td.label 
                = change
              %td.value
                = old_values(value)
              %td.value
                = new_values(value)

app/views/sm_banks/edit.html.haml
%h1 Editing Sub Member Bank

= render 'form'

app/views/sm_banks/index.html.haml
%br
= link_to 'New Sub Member Bank', new_sm_bank_path
%br
%br
%h1 Listing Sub Member Banks
%h2.collapsible
  Advanced Search
  %span.caret
.collapsible-content
  = render :partial => 'advanced_search'
%br
= "Total Count: #{@sm_banks_count}"
%br
= will_paginate @sm_banks
%br

%table.table.table-bordered.table-striped.table-hover
  .thead
    %th{:style=>'text-align:left; background-color: lightblue;'}
    %th{:style=>'text-align:left; background-color: lightblue;'}
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Enabled?
    %th{:style=>'text-align:left; background-color: lightblue;'}
      SMB Code
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Name
    %th{:style=>'text-align:left; background-color: lightblue;'}
      SMB IFSC Code
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Low Balance Alert At
    %th{:style=>'text-align:left; background-color: lightblue;'}
      Identity User ID
    %th{:style=>'text-align:left; background-color: lightblue;'}
      NEFT Allowed?
    %th{:style=>'text-align:left; background-color: lightblue;'}
      IMPS Allowed?
    %th{:style=>'text-align:left; background-color: lightblue;'}
      RTGS Allowed?

  .tbody
    - @sm_banks.each do |sm_bank|
      %tr
        %td{:style=>'text-align:left;'}
          = link_to 'Show', sm_bank
        %td{:style=>'text-align:left;'}
          = link_to 'Edit', edit_sm_bank_path(sm_bank)
        %td{:style=>'text-align:left;'}
          = sm_bank.is_enabled
        %td{:style=>'text-align:left;'}
          = sm_bank.code
        %td{:style=>'text-align:left; word-break: break-word; width: 20%;'}
          = sm_bank.name
        %td{:style=>'text-align:left;'}
          = sm_bank.bank_code
        %td{:style=>'text-align:left;'}
          = sm_bank.low_balance_alert_at
        %td{:style=>'text-align:left;'}
          = sm_bank.identity_user_id
        %td{:style=>'text-align:left;'}
          = sm_bank.neft_allowed
        %td{:style=>'text-align:left;'}
          = sm_bank.imps_allowed
        %td{:style=>'text-align:left;'}
          = sm_bank.rtgs_allowed

:javascript
  $(document).ready(function(){
    $('input[type="text"]'). attr("placeholder", "Multisearch Search Enabled");
  });

app/views/sm_banks/new.html.haml
%h1 New Sub Member Bank

= render 'form'

app/views/sm_banks/show.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8; height: 900px;'}
    #form-details
      %h3 Sub Member Bank Details 
      %br
      %p{:style => 'text-align:left; padding-left:6px; padding-bottom:17px'}
        - can = can? :edit, @sm_bank
        %a.btn{:href => "#{!(can) ? '#' : '/sm_banks/' + @sm_bank.id.to_s + '/edit'}", :role => "button", :class => "btn btn-primary #{(can) ? '' : 'disabled'}"} Edit
        = render 'unapproved_records/approve_and_resend', :@record => @sm_bank
      %table.table.no-border{:style=>"table-layout: fixed; width: 100%;"}
        - if !@sm_bank.nil?
          %tr
            %td.label Version
            %td.value
              = link_to "#{audit_count(@sm_bank)}", :controller => :sm_banks, :action => :audit_logs, :version_id => audit_count(@sm_bank), :id => @sm_bank.id
          %tr
            %td.label Form Errors
            %td.value
              = ' '
            %td#msg-error
              = error_message_for(@sm_bank, :base, :prepend_text => "")
          %tr
            %td.label Enabled?
            %td.value
              = @sm_bank.is_enabled
            %td#msg-error
              = error_message_for(@sm_bank, :is_enabled, :prepend_text => "")
          %tr
            %td.label SMB Code
            %td.value
              = @sm_bank.code
            %td#msg-error
              = error_message_for(@sm_bank, :code, :prepend_text => "")
          %tr
            %td.label Name
            %td.value
              = @sm_bank.name
            %td#msg-error
              = error_message_for(@sm_bank, :name, :prepend_text => "")
          %tr
            %td.label SMB IFSC Code
            %td.value
              = @sm_bank.bank_code
            %td#msg-error
              = error_message_for(@sm_bank, :bank_code, :prepend_text => "")
          %tr
            %td.label Low Balance Alert At
            %td.value
              = @sm_bank.low_balance_alert_at
            %td#msg-error
              = error_message_for(@sm_bank, :low_balance_alert_at, :prepend_text => "")
          %tr
            %td.label Identity User ID
            %td.value
              = @sm_bank.identity_user_id
            %td#msg-error
              = error_message_for(@sm_bank, :identity_user_id, :prepend_text => "")
          %tr
            %td.label NEFT Allowed?
            %td.value
              = @sm_bank.neft_allowed
            %td#msg-error
              = error_message_for(@sm_bank, :neft_allowed, :prepend_text => "")
          %tr
            %td.label IMPS Allowed?
            %td.value
              = @sm_bank.imps_allowed
            %td#msg-error
              = error_message_for(@sm_bank, :imps_allowed, :prepend_text => "")
          %tr
            %td.label RTGS Allowed?
            %td.value
              = @sm_bank.rtgs_allowed
            %td#msg-error
              = error_message_for(@sm_bank, :rtgs_allowed, :prepend_text => "")
          %tr
            %td.label Notification Sent At
            %td
              = @sm_bank.notification_sent_at.try(:strftime, "%d/%m/%Y %I:%M%p")
            %td#msg-error
              = error_message_for(@sm_bank, :notification_sent_at, :prepend_text => "")
          %tr
            %td.label Created By
            %td.value
              = @sm_bank.created_user.try(:username)
            %td#msg-error
              = error_message_for(@sm_bank, :created_by, :prepend_text => "")
          %tr
            %td.label Updated By
            %td.value
              = @sm_bank.updated_user.try(:username)
            %td#msg-error
              = error_message_for(@sm_bank, :updated_by, :prepend_text => "")
          %tr
            %td.label Created At
            %td.value
              = @sm_bank.created_at.try(:strftime, "%d/%m/%Y %I:%M%p")
            %td#msg-error
              = error_message_for(@sm_bank, :created_at, :prepend_text => "")
          %tr
            %td.label Updated At
            %td.value
              = @sm_bank.updated_at.try(:strftime, "%d/%m/%Y %I:%M%p")
            %td#msg-error
              = error_message_for(@sm_bank, :updated_at, :prepend_text => "")